### ISSUE TITLE
Cannot build the project without signing

### ISSUE THREAD

**Issue by Taskeren** [zly2006/KhlKt#2]
Task `signArtifacts` is required by task `build`. As we don't have your `maven.gpg`, it fails.

**Comment by zly2006** [comment]
You can use Build -> Build Artifacts -> KhlKt-all to build this project. And I am trying to publish this project to maven central so that you can use maven to manage this sdk.

**Comment by Taskeren** [comment]
I've resolve this problem.
But I think you should add the signing part when you can publish to maven central.
Also, [jitpack](https://jitpack.io) can help you with publishing in early dev stage.

**Comment by Qubik65536** [comment]
> I've resolve this problem.
> But I think you should add the signing part when you can publish to maven central.
> Also, [jitpack](https://jitpack.io) can help you with publishing in early dev stage.

Just a note, you can now refer to our [docs](https://kookybot.readthedocs.io/zh_CN/latest/quick-start/index.html#jitpack-gradle-maven) for adding the KookyBot lib using Maven/Gradle.
